# netlify.toml
[build]  
  command = "npm install --force && ng build"
  publish = "dist/sibre-app"

# Configuração das regras de redirecionamento
[[redirects]]
  # Redireciona todas as solicitações para o index.html
  from = "/*"
  to = "/index.html"
  status = 200
